/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hddinventory;

import java.awt.event.*;
import java.util.Vector;

/**
 *
 * @author linkxs
 */
public class HddFactory extends javax.swing.JFrame implements FocusListener, ActionListener {
    /**
     * Creates new form HddFactory
     */
    private PrimaryInterface pi;

    public HddFactory(PrimaryInterface pi) {
	initComponents();
	this.pi = pi;

	this.setVisible(false);
    }

    public void fillFields(Hdd h) {
	modelNumField.setText(h.getModelNum());
	serialNumField.setText(h.getSerialNum());
	sizeField.setText(h.getSizeGb() + " GB");
	seriesField.setText(h.getSeries());
	dateField.setText(h.getDateNum());
	formFactorComboBox.setSelectedItem(h.getForm());
	interfaceField.setText(h.getIface());
	manufacturerField.setText(h.getManufacturer());
	notesArea.setText(h.getNotes());
	partNumField.setText(h.getPartNum());
	pcbNumField.setText(h.getPcbNum());
	partsPresentList.setListData(h.getPartsPresent());
	ownerField.setText(h.getOwner());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        modelNumField = new javax.swing.JTextField();
        autoDetectButton = new javax.swing.JButton();
        manufacturerField = new javax.swing.JTextField();
        serialNumField = new javax.swing.JTextField();
        sizeField = new javax.swing.JTextField();
        seriesField = new javax.swing.JTextField();
        partNumField = new javax.swing.JTextField();
        pcbNumField = new javax.swing.JTextField();
        interfaceField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        formFactorComboBox = new javax.swing.JComboBox();
        ownerField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        partsPresentList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        startDcButton = new javax.swing.JButton();
        startShdButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        modelNumField.setText("Model Number");
        modelNumField.addFocusListener(this);

        autoDetectButton.setText("Autodetect");

        manufacturerField.setText("Manufacturer");

        serialNumField.setText("Serial Number");

        sizeField.setText("Size");

        seriesField.setText("Series");

        partNumField.setText("Part Number");

        pcbNumField.setText("PCB Number");

        interfaceField.setText("Interface");
        interfaceField.addActionListener(this);

        dateField.setText("Date");
        dateField.addActionListener(this);

        formFactorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ownerField.setText("Owner");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modelNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(partNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(manufacturerField)
                                    .addComponent(serialNumField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(sizeField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcbNumField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ownerField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(interfaceField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(seriesField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                            .addComponent(dateField)))
                                    .addComponent(formFactorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(autoDetectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seriesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcbNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoDetectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formFactorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(interfaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel1);

        partsPresentList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(partsPresentList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Parts Present", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pictures", jPanel3);

        notesArea.setColumns(20);
        notesArea.setRows(5);
        notesArea.setText("Notes");
        jScrollPane2.setViewportView(notesArea);

        jTabbedPane1.addTab("Notes", jScrollPane2);

        startDcButton.setText("Start DC");

        startShdButton.setText("Start SHD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startDcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startShdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startDcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(startShdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Utility", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == interfaceField) {
            HddFactory.this.interfaceFieldActionPerformed(evt);
        }
        else if (evt.getSource() == dateField) {
            HddFactory.this.dateFieldActionPerformed(evt);
        }
    }

    public void focusGained(java.awt.event.FocusEvent evt) {
        if (evt.getSource() == modelNumField) {
            HddFactory.this.modelNumFieldFocusGained(evt);
        }
    }

    public void focusLost(java.awt.event.FocusEvent evt) {
        if (evt.getSource() == modelNumField) {
            HddFactory.this.modelNumFieldFocusLost(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void modelNumFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelNumFieldFocusGained
	modelNumField.setText("");
    }//GEN-LAST:event_modelNumFieldFocusGained

    private void modelNumFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelNumFieldFocusLost
	modelNumField.setText("Model Number");
    }//GEN-LAST:event_modelNumFieldFocusLost

    private void interfaceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interfaceFieldActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_interfaceFieldActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    public void dispose() {
	modelNumField.setText("Model Number");
	serialNumField.setText("Serial Number");
	sizeField.setText("Size");
	seriesField.setText("Series");
	dateField.setText("Date");
	formFactorComboBox.setSelectedIndex(0);
	interfaceField.setText("Interface");
	manufacturerField.setText("Manufacturer");
	notesArea.setText("Notes");
	partNumField.setText("Part Number");
	pcbNumField.setText("PCB Number");
	partsPresentList.setListData(new Vector<String>());

	this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//	/*
//	 * Set the Nimbus look and feel
//	 */
//	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//	 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//	 */
//	try {
//	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//		if ("Nimbus".equals(info.getName())) {
//		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//		    break;
//		}
//	    }
//	} catch (ClassNotFoundException ex) {
//	    java.util.logging.Logger.getLogger(HddFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	} catch (InstantiationException ex) {
//	    java.util.logging.Logger.getLogger(HddFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	} catch (IllegalAccessException ex) {
//	    java.util.logging.Logger.getLogger(HddFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//	    java.util.logging.Logger.getLogger(HddFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	}
//	//</editor-fold>
//
//	/*
//	 * Create and display the form
//	 */
//	java.awt.EventQueue.invokeLater(new Runnable() {
//	    public void run() {
//		new HddFactory().setVisible(true);
//	    }
//	});
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autoDetectButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JComboBox formFactorComboBox;
    private javax.swing.JTextField interfaceField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JTextField modelNumField;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JTextField ownerField;
    private javax.swing.JTextField partNumField;
    private javax.swing.JList partsPresentList;
    private javax.swing.JTextField pcbNumField;
    private javax.swing.JTextField serialNumField;
    private javax.swing.JTextField seriesField;
    private javax.swing.JTextField sizeField;
    private javax.swing.JButton startDcButton;
    private javax.swing.JButton startShdButton;
    // End of variables declaration//GEN-END:variables
}
